### ISSUE TITLE
API Call Help

### ISSUE THREAD

**Issue by DocDrydenn** [Snille/MMM-Videoplayer#8]
Looking for assistance on how to properly form an API call URL to force `MMM-Videoplayer` to `REPLAY` the currently loaded video.

Initially, I set this up in `MMM-GPIO-Notifications` inside `config.js` and it worked perfectly:
```
'16': {
  delay: 2000,
  notifications_low: [
    {
      notification: 'VIDEOPLAYER1',
      payload: 'REPLAY'
    }
  ]
}
```
Now, I'm moving away from `MMM-GPIO-Notifications` and to an external python script to handle all my button commands. All went smoothly except for this one command.

I know it has something to do with how `MMM-Videoplayer` handles notifications... as per the last line of it's `config.js` entry:

```
module: 'MMM-Videoplayer',
position: 'fullscreen_above',
config: {
    video: "/modules/MMM-Videoplayer/video/blob.mp4",
    ...
    notification: "VIDEOPLAYER1"  // Unique notification string for this player (to be able to play, pause, restart and next from another modules).
}
```
I've tried so many different combinations of `http:ip:8080/remote?...` and just can't get it to work. Any help would be appreciated.

**Comment by Snille** [comment]
You can try everything out with the Remote-Control API (Docs): http://YOUR.IP.TO_THE.MIRROR:8080/api/docs/#/Module%20Control/get_api_notification___notification_____p_

Then you can see the the curl-command that you can use in your script... :)

This is how it looks for me (using the api/docs):
![image](https://github.com/user-attachments/assets/51b8b6a6-6237-407a-8a26-a06ac8d15c52)

PS: for the moment (since v2.29.0) the API from the "MMM-Remote-Control" does not work properly, see here: https://github.com/Jopyth/MMM-Remote-Control/issues/306
But if you use the suggested [PR](https://github.com/khassel/MMM-Remote-Control/tree/mm_fixes) from [khassel](https://github.com/khassel) you should be good... At least it works for me.

**Comment by DocDrydenn** [comment]
That was it! 

I needed to do it with `/api/notification/xxxx/yyyy`. 
For whatever reason, I was mentally fixed on the `/remote?xxxx...` format.

Thanks for the help! (Yes, I had already applied the MMM-Remote-Control PR)
